// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/schema.proto

package exporter_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordMetadata_ValueType int32

const (
	RecordMetadata_UNKNOWN_VALUE_TYPE               RecordMetadata_ValueType = 0
	RecordMetadata_JOB                              RecordMetadata_ValueType = 1
	RecordMetadata_DEPLOYMENT                       RecordMetadata_ValueType = 2
	RecordMetadata_WORKFLOW_INSTANCE                RecordMetadata_ValueType = 3
	RecordMetadata_INCIDENT                         RecordMetadata_ValueType = 4
	RecordMetadata_MESSAGE                          RecordMetadata_ValueType = 5
	RecordMetadata_MESSAGE_SUBSCRIPTION             RecordMetadata_ValueType = 6
	RecordMetadata_WORKFLOW_INSTANCE_SUBSCRIPTION   RecordMetadata_ValueType = 7
	RecordMetadata_JOB_BATCH                        RecordMetadata_ValueType = 8
	RecordMetadata_TIMER                            RecordMetadata_ValueType = 9
	RecordMetadata_MESSAGE_START_EVENT_SUBSCRIPTION RecordMetadata_ValueType = 10
	RecordMetadata_VARIABLE                         RecordMetadata_ValueType = 11
	RecordMetadata_VARIABLE_DOCUMENT                RecordMetadata_ValueType = 12
	RecordMetadata_WORKFLOW_INSTANCE_CREATION       RecordMetadata_ValueType = 13
	RecordMetadata_ERROR                            RecordMetadata_ValueType = 14
	RecordMetadata_WORKFLOW_INSTANCE_RESULT         RecordMetadata_ValueType = 15
)

var RecordMetadata_ValueType_name = map[int32]string{
	0:  "UNKNOWN_VALUE_TYPE",
	1:  "JOB",
	2:  "DEPLOYMENT",
	3:  "WORKFLOW_INSTANCE",
	4:  "INCIDENT",
	5:  "MESSAGE",
	6:  "MESSAGE_SUBSCRIPTION",
	7:  "WORKFLOW_INSTANCE_SUBSCRIPTION",
	8:  "JOB_BATCH",
	9:  "TIMER",
	10: "MESSAGE_START_EVENT_SUBSCRIPTION",
	11: "VARIABLE",
	12: "VARIABLE_DOCUMENT",
	13: "WORKFLOW_INSTANCE_CREATION",
	14: "ERROR",
	15: "WORKFLOW_INSTANCE_RESULT",
}

var RecordMetadata_ValueType_value = map[string]int32{
	"UNKNOWN_VALUE_TYPE":               0,
	"JOB":                              1,
	"DEPLOYMENT":                       2,
	"WORKFLOW_INSTANCE":                3,
	"INCIDENT":                         4,
	"MESSAGE":                          5,
	"MESSAGE_SUBSCRIPTION":             6,
	"WORKFLOW_INSTANCE_SUBSCRIPTION":   7,
	"JOB_BATCH":                        8,
	"TIMER":                            9,
	"MESSAGE_START_EVENT_SUBSCRIPTION": 10,
	"VARIABLE":                         11,
	"VARIABLE_DOCUMENT":                12,
	"WORKFLOW_INSTANCE_CREATION":       13,
	"ERROR":                            14,
	"WORKFLOW_INSTANCE_RESULT":         15,
}

func (x RecordMetadata_ValueType) String() string {
	return proto.EnumName(RecordMetadata_ValueType_name, int32(x))
}

func (RecordMetadata_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{2, 0}
}

type RecordMetadata_RecordType int32

const (
	RecordMetadata_UNKNOWN_RECORD_TYPE RecordMetadata_RecordType = 0
	RecordMetadata_EVENT               RecordMetadata_RecordType = 1
	RecordMetadata_COMMAND             RecordMetadata_RecordType = 2
	RecordMetadata_COMMAND_REJECTION   RecordMetadata_RecordType = 3
)

var RecordMetadata_RecordType_name = map[int32]string{
	0: "UNKNOWN_RECORD_TYPE",
	1: "EVENT",
	2: "COMMAND",
	3: "COMMAND_REJECTION",
}

var RecordMetadata_RecordType_value = map[string]int32{
	"UNKNOWN_RECORD_TYPE": 0,
	"EVENT":               1,
	"COMMAND":             2,
	"COMMAND_REJECTION":   3,
}

func (x RecordMetadata_RecordType) String() string {
	return proto.EnumName(RecordMetadata_RecordType_name, int32(x))
}

func (RecordMetadata_RecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{2, 1}
}

type VariableDocumentRecord_UpdateSemantics int32

const (
	VariableDocumentRecord_UNKNOWN_UPDATE_SEMANTICS VariableDocumentRecord_UpdateSemantics = 0
	VariableDocumentRecord_LOCAL                    VariableDocumentRecord_UpdateSemantics = 1
	VariableDocumentRecord_PROPAGATE                VariableDocumentRecord_UpdateSemantics = 2
)

var VariableDocumentRecord_UpdateSemantics_name = map[int32]string{
	0: "UNKNOWN_UPDATE_SEMANTICS",
	1: "LOCAL",
	2: "PROPAGATE",
}

var VariableDocumentRecord_UpdateSemantics_value = map[string]int32{
	"UNKNOWN_UPDATE_SEMANTICS": 0,
	"LOCAL":                    1,
	"PROPAGATE":                2,
}

func (x VariableDocumentRecord_UpdateSemantics) String() string {
	return proto.EnumName(VariableDocumentRecord_UpdateSemantics_name, int32(x))
}

func (VariableDocumentRecord_UpdateSemantics) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{13, 0}
}

type WorkflowInstanceRecord_BpmnElementType int32

const (
	WorkflowInstanceRecord_UNKNOWN_BPMN_ELEMENT_TYPE WorkflowInstanceRecord_BpmnElementType = 0
	WorkflowInstanceRecord_UNSPECIFIED               WorkflowInstanceRecord_BpmnElementType = 1
	WorkflowInstanceRecord_PROCESS                   WorkflowInstanceRecord_BpmnElementType = 2
	WorkflowInstanceRecord_SUB_PROCESS               WorkflowInstanceRecord_BpmnElementType = 3
	WorkflowInstanceRecord_START_EVENT               WorkflowInstanceRecord_BpmnElementType = 4
	WorkflowInstanceRecord_INTERMEDIATE_CATCH_EVENT  WorkflowInstanceRecord_BpmnElementType = 5
	WorkflowInstanceRecord_BOUNDARY_EVENT            WorkflowInstanceRecord_BpmnElementType = 6
	WorkflowInstanceRecord_END_EVENT                 WorkflowInstanceRecord_BpmnElementType = 7
	WorkflowInstanceRecord_SERVICE_TASK              WorkflowInstanceRecord_BpmnElementType = 8
	WorkflowInstanceRecord_RECEIVE_TASK              WorkflowInstanceRecord_BpmnElementType = 9
	WorkflowInstanceRecord_EXCLUSIVE_GATEWAY         WorkflowInstanceRecord_BpmnElementType = 10
	WorkflowInstanceRecord_PARALLEL_GATEWAY          WorkflowInstanceRecord_BpmnElementType = 11
	WorkflowInstanceRecord_EVENT_BASED_GATEWAY       WorkflowInstanceRecord_BpmnElementType = 12
	WorkflowInstanceRecord_SEQUENCE_FLOW             WorkflowInstanceRecord_BpmnElementType = 13
	WorkflowInstanceRecord_MULTI_INSTANCE_BODY       WorkflowInstanceRecord_BpmnElementType = 14
	WorkflowInstanceRecord_CALL_ACTIVITY             WorkflowInstanceRecord_BpmnElementType = 15
)

var WorkflowInstanceRecord_BpmnElementType_name = map[int32]string{
	0:  "UNKNOWN_BPMN_ELEMENT_TYPE",
	1:  "UNSPECIFIED",
	2:  "PROCESS",
	3:  "SUB_PROCESS",
	4:  "START_EVENT",
	5:  "INTERMEDIATE_CATCH_EVENT",
	6:  "BOUNDARY_EVENT",
	7:  "END_EVENT",
	8:  "SERVICE_TASK",
	9:  "RECEIVE_TASK",
	10: "EXCLUSIVE_GATEWAY",
	11: "PARALLEL_GATEWAY",
	12: "EVENT_BASED_GATEWAY",
	13: "SEQUENCE_FLOW",
	14: "MULTI_INSTANCE_BODY",
	15: "CALL_ACTIVITY",
}

var WorkflowInstanceRecord_BpmnElementType_value = map[string]int32{
	"UNKNOWN_BPMN_ELEMENT_TYPE": 0,
	"UNSPECIFIED":               1,
	"PROCESS":                   2,
	"SUB_PROCESS":               3,
	"START_EVENT":               4,
	"INTERMEDIATE_CATCH_EVENT":  5,
	"BOUNDARY_EVENT":            6,
	"END_EVENT":                 7,
	"SERVICE_TASK":              8,
	"RECEIVE_TASK":              9,
	"EXCLUSIVE_GATEWAY":         10,
	"PARALLEL_GATEWAY":          11,
	"EVENT_BASED_GATEWAY":       12,
	"SEQUENCE_FLOW":             13,
	"MULTI_INSTANCE_BODY":       14,
	"CALL_ACTIVITY":             15,
}

func (x WorkflowInstanceRecord_BpmnElementType) String() string {
	return proto.EnumName(WorkflowInstanceRecord_BpmnElementType_name, int32(x))
}

func (WorkflowInstanceRecord_BpmnElementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{14, 0}
}

// Convenience message for systems which use a key/id system for each record
type RecordId struct {
	PartitionId          int32    `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Position             int64    `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordId) Reset()         { *m = RecordId{} }
func (m *RecordId) String() string { return proto.CompactTextString(m) }
func (*RecordId) ProtoMessage()    {}
func (*RecordId) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{0}
}

func (m *RecordId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordId.Unmarshal(m, b)
}
func (m *RecordId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordId.Marshal(b, m, deterministic)
}
func (m *RecordId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordId.Merge(m, src)
}
func (m *RecordId) XXX_Size() int {
	return xxx_messageInfo_RecordId.Size(m)
}
func (m *RecordId) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordId.DiscardUnknown(m)
}

var xxx_messageInfo_RecordId proto.InternalMessageInfo

func (m *RecordId) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *RecordId) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

// Convenience message for packing any kind of record
type Record struct {
	Record               *any.Any `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRecord() *any.Any {
	if m != nil {
		return m.Record
	}
	return nil
}

// Packs all non-value info into a single field; the idea here is so we can embed the *Record messages into other
// messages (e.g. JobRecord and JobBatchRecord) by simply omitting the optional metadata field, but by setting it the
// message becomes a full fledged record. Also cuts down how much properties need to be duplicated if we want to have
// flat records.
type RecordMetadata struct {
	PartitionId          int32                     `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Position             int64                     `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Key                  int64                     `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp            int64                     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RecordType           RecordMetadata_RecordType `protobuf:"varint,5,opt,name=recordType,proto3,enum=exporter_protocol.RecordMetadata_RecordType" json:"recordType,omitempty"`
	Intent               string                    `protobuf:"bytes,6,opt,name=intent,proto3" json:"intent,omitempty"`
	ValueType            RecordMetadata_ValueType  `protobuf:"varint,7,opt,name=valueType,proto3,enum=exporter_protocol.RecordMetadata_ValueType" json:"valueType,omitempty"`
	SourceRecordPosition int64                     `protobuf:"varint,8,opt,name=sourceRecordPosition,proto3" json:"sourceRecordPosition,omitempty"`
	RejectionType        string                    `protobuf:"bytes,9,opt,name=rejectionType,proto3" json:"rejectionType,omitempty"`
	RejectionReason      string                    `protobuf:"bytes,10,opt,name=rejectionReason,proto3" json:"rejectionReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RecordMetadata) Reset()         { *m = RecordMetadata{} }
func (m *RecordMetadata) String() string { return proto.CompactTextString(m) }
func (*RecordMetadata) ProtoMessage()    {}
func (*RecordMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{2}
}

func (m *RecordMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordMetadata.Unmarshal(m, b)
}
func (m *RecordMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordMetadata.Marshal(b, m, deterministic)
}
func (m *RecordMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordMetadata.Merge(m, src)
}
func (m *RecordMetadata) XXX_Size() int {
	return xxx_messageInfo_RecordMetadata.Size(m)
}
func (m *RecordMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RecordMetadata proto.InternalMessageInfo

func (m *RecordMetadata) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *RecordMetadata) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *RecordMetadata) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *RecordMetadata) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RecordMetadata) GetRecordType() RecordMetadata_RecordType {
	if m != nil {
		return m.RecordType
	}
	return RecordMetadata_UNKNOWN_RECORD_TYPE
}

func (m *RecordMetadata) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *RecordMetadata) GetValueType() RecordMetadata_ValueType {
	if m != nil {
		return m.ValueType
	}
	return RecordMetadata_UNKNOWN_VALUE_TYPE
}

func (m *RecordMetadata) GetSourceRecordPosition() int64 {
	if m != nil {
		return m.SourceRecordPosition
	}
	return 0
}

func (m *RecordMetadata) GetRejectionType() string {
	if m != nil {
		return m.RejectionType
	}
	return ""
}

func (m *RecordMetadata) GetRejectionReason() string {
	if m != nil {
		return m.RejectionReason
	}
	return ""
}

type DeploymentRecord struct {
	Metadata             *RecordMetadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Resources            []*DeploymentRecord_Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	DeployedWorkflows    []*DeploymentRecord_Workflow `protobuf:"bytes,3,rep,name=deployedWorkflows,proto3" json:"deployedWorkflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeploymentRecord) Reset()         { *m = DeploymentRecord{} }
func (m *DeploymentRecord) String() string { return proto.CompactTextString(m) }
func (*DeploymentRecord) ProtoMessage()    {}
func (*DeploymentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{3}
}

func (m *DeploymentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRecord.Unmarshal(m, b)
}
func (m *DeploymentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRecord.Marshal(b, m, deterministic)
}
func (m *DeploymentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRecord.Merge(m, src)
}
func (m *DeploymentRecord) XXX_Size() int {
	return xxx_messageInfo_DeploymentRecord.Size(m)
}
func (m *DeploymentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRecord proto.InternalMessageInfo

func (m *DeploymentRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DeploymentRecord) GetResources() []*DeploymentRecord_Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DeploymentRecord) GetDeployedWorkflows() []*DeploymentRecord_Workflow {
	if m != nil {
		return m.DeployedWorkflows
	}
	return nil
}

type DeploymentRecord_Resource struct {
	Resource             []byte   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	ResourceName         string   `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentRecord_Resource) Reset()         { *m = DeploymentRecord_Resource{} }
func (m *DeploymentRecord_Resource) String() string { return proto.CompactTextString(m) }
func (*DeploymentRecord_Resource) ProtoMessage()    {}
func (*DeploymentRecord_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{3, 0}
}

func (m *DeploymentRecord_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRecord_Resource.Unmarshal(m, b)
}
func (m *DeploymentRecord_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRecord_Resource.Marshal(b, m, deterministic)
}
func (m *DeploymentRecord_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRecord_Resource.Merge(m, src)
}
func (m *DeploymentRecord_Resource) XXX_Size() int {
	return xxx_messageInfo_DeploymentRecord_Resource.Size(m)
}
func (m *DeploymentRecord_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRecord_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRecord_Resource proto.InternalMessageInfo

func (m *DeploymentRecord_Resource) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *DeploymentRecord_Resource) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *DeploymentRecord_Resource) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type DeploymentRecord_Workflow struct {
	BpmnProcessId        string   `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey          int64    `protobuf:"varint,3,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	ResourceName         string   `protobuf:"bytes,5,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentRecord_Workflow) Reset()         { *m = DeploymentRecord_Workflow{} }
func (m *DeploymentRecord_Workflow) String() string { return proto.CompactTextString(m) }
func (*DeploymentRecord_Workflow) ProtoMessage()    {}
func (*DeploymentRecord_Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{3, 1}
}

func (m *DeploymentRecord_Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRecord_Workflow.Unmarshal(m, b)
}
func (m *DeploymentRecord_Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRecord_Workflow.Marshal(b, m, deterministic)
}
func (m *DeploymentRecord_Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRecord_Workflow.Merge(m, src)
}
func (m *DeploymentRecord_Workflow) XXX_Size() int {
	return xxx_messageInfo_DeploymentRecord_Workflow.Size(m)
}
func (m *DeploymentRecord_Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRecord_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRecord_Workflow proto.InternalMessageInfo

func (m *DeploymentRecord_Workflow) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *DeploymentRecord_Workflow) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DeploymentRecord_Workflow) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *DeploymentRecord_Workflow) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type ErrorRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExceptionMessage     string          `protobuf:"bytes,2,opt,name=exceptionMessage,proto3" json:"exceptionMessage,omitempty"`
	Stacktrace           string          `protobuf:"bytes,3,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	ErrorEventPosition   int64           `protobuf:"varint,4,opt,name=errorEventPosition,proto3" json:"errorEventPosition,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ErrorRecord) Reset()         { *m = ErrorRecord{} }
func (m *ErrorRecord) String() string { return proto.CompactTextString(m) }
func (*ErrorRecord) ProtoMessage()    {}
func (*ErrorRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{4}
}

func (m *ErrorRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorRecord.Unmarshal(m, b)
}
func (m *ErrorRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorRecord.Marshal(b, m, deterministic)
}
func (m *ErrorRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorRecord.Merge(m, src)
}
func (m *ErrorRecord) XXX_Size() int {
	return xxx_messageInfo_ErrorRecord.Size(m)
}
func (m *ErrorRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorRecord proto.InternalMessageInfo

func (m *ErrorRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ErrorRecord) GetExceptionMessage() string {
	if m != nil {
		return m.ExceptionMessage
	}
	return ""
}

func (m *ErrorRecord) GetStacktrace() string {
	if m != nil {
		return m.Stacktrace
	}
	return ""
}

func (m *ErrorRecord) GetErrorEventPosition() int64 {
	if m != nil {
		return m.ErrorEventPosition
	}
	return 0
}

func (m *ErrorRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

type IncidentRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ErrorType            string          `protobuf:"bytes,2,opt,name=errorType,proto3" json:"errorType,omitempty"`
	ErrorMessage         string          `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,4,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	ElementId            string          `protobuf:"bytes,6,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementInstanceKey   int64           `protobuf:"varint,7,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	JobKey               int64           `protobuf:"varint,8,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,9,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	VariableScopeKey     int64           `protobuf:"varint,10,opt,name=variableScopeKey,proto3" json:"variableScopeKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IncidentRecord) Reset()         { *m = IncidentRecord{} }
func (m *IncidentRecord) String() string { return proto.CompactTextString(m) }
func (*IncidentRecord) ProtoMessage()    {}
func (*IncidentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{5}
}

func (m *IncidentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncidentRecord.Unmarshal(m, b)
}
func (m *IncidentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncidentRecord.Marshal(b, m, deterministic)
}
func (m *IncidentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncidentRecord.Merge(m, src)
}
func (m *IncidentRecord) XXX_Size() int {
	return xxx_messageInfo_IncidentRecord.Size(m)
}
func (m *IncidentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_IncidentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_IncidentRecord proto.InternalMessageInfo

func (m *IncidentRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *IncidentRecord) GetErrorType() string {
	if m != nil {
		return m.ErrorType
	}
	return ""
}

func (m *IncidentRecord) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *IncidentRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *IncidentRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *IncidentRecord) GetElementId() string {
	if m != nil {
		return m.ElementId
	}
	return ""
}

func (m *IncidentRecord) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *IncidentRecord) GetJobKey() int64 {
	if m != nil {
		return m.JobKey
	}
	return 0
}

func (m *IncidentRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *IncidentRecord) GetVariableScopeKey() int64 {
	if m != nil {
		return m.VariableScopeKey
	}
	return 0
}

type JobRecord struct {
	Metadata                  *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type                      string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Worker                    string          `protobuf:"bytes,3,opt,name=worker,proto3" json:"worker,omitempty"`
	Retries                   int32           `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	Deadline                  int64           `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	ErrorMessage              string          `protobuf:"bytes,6,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	CustomHeaders             *_struct.Struct `protobuf:"bytes,7,opt,name=customHeaders,proto3" json:"customHeaders,omitempty"`
	Variables                 *_struct.Struct `protobuf:"bytes,8,opt,name=variables,proto3" json:"variables,omitempty"`
	ElementId                 string          `protobuf:"bytes,9,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementInstanceKey        int64           `protobuf:"varint,10,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	BpmnProcessId             string          `protobuf:"bytes,11,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	WorkflowDefinitionVersion int32           `protobuf:"varint,12,opt,name=workflowDefinitionVersion,proto3" json:"workflowDefinitionVersion,omitempty"`
	WorkflowInstanceKey       int64           `protobuf:"varint,13,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	WorkflowKey               int64           `protobuf:"varint,14,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}        `json:"-"`
	XXX_unrecognized          []byte          `json:"-"`
	XXX_sizecache             int32           `json:"-"`
}

func (m *JobRecord) Reset()         { *m = JobRecord{} }
func (m *JobRecord) String() string { return proto.CompactTextString(m) }
func (*JobRecord) ProtoMessage()    {}
func (*JobRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{6}
}

func (m *JobRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRecord.Unmarshal(m, b)
}
func (m *JobRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRecord.Marshal(b, m, deterministic)
}
func (m *JobRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRecord.Merge(m, src)
}
func (m *JobRecord) XXX_Size() int {
	return xxx_messageInfo_JobRecord.Size(m)
}
func (m *JobRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRecord.DiscardUnknown(m)
}

var xxx_messageInfo_JobRecord proto.InternalMessageInfo

func (m *JobRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *JobRecord) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JobRecord) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *JobRecord) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *JobRecord) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *JobRecord) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *JobRecord) GetCustomHeaders() *_struct.Struct {
	if m != nil {
		return m.CustomHeaders
	}
	return nil
}

func (m *JobRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *JobRecord) GetElementId() string {
	if m != nil {
		return m.ElementId
	}
	return ""
}

func (m *JobRecord) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *JobRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *JobRecord) GetWorkflowDefinitionVersion() int32 {
	if m != nil {
		return m.WorkflowDefinitionVersion
	}
	return 0
}

func (m *JobRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *JobRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

type JobBatchRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Worker               string          `protobuf:"bytes,3,opt,name=worker,proto3" json:"worker,omitempty"`
	Timeout              int64           `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxJobsToActivate    int32           `protobuf:"varint,5,opt,name=maxJobsToActivate,proto3" json:"maxJobsToActivate,omitempty"`
	JobKeys              []int64         `protobuf:"varint,6,rep,packed,name=jobKeys,proto3" json:"jobKeys,omitempty"`
	Jobs                 []*JobRecord    `protobuf:"bytes,7,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Truncated            bool            `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JobBatchRecord) Reset()         { *m = JobBatchRecord{} }
func (m *JobBatchRecord) String() string { return proto.CompactTextString(m) }
func (*JobBatchRecord) ProtoMessage()    {}
func (*JobBatchRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{7}
}

func (m *JobBatchRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobBatchRecord.Unmarshal(m, b)
}
func (m *JobBatchRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobBatchRecord.Marshal(b, m, deterministic)
}
func (m *JobBatchRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobBatchRecord.Merge(m, src)
}
func (m *JobBatchRecord) XXX_Size() int {
	return xxx_messageInfo_JobBatchRecord.Size(m)
}
func (m *JobBatchRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_JobBatchRecord.DiscardUnknown(m)
}

var xxx_messageInfo_JobBatchRecord proto.InternalMessageInfo

func (m *JobBatchRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *JobBatchRecord) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JobBatchRecord) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *JobBatchRecord) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *JobBatchRecord) GetMaxJobsToActivate() int32 {
	if m != nil {
		return m.MaxJobsToActivate
	}
	return 0
}

func (m *JobBatchRecord) GetJobKeys() []int64 {
	if m != nil {
		return m.JobKeys
	}
	return nil
}

func (m *JobBatchRecord) GetJobs() []*JobRecord {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *JobBatchRecord) GetTruncated() bool {
	if m != nil {
		return m.Truncated
	}
	return false
}

type MessageRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CorrelationKey       string          `protobuf:"bytes,3,opt,name=correlationKey,proto3" json:"correlationKey,omitempty"`
	MessageId            string          `protobuf:"bytes,4,opt,name=messageId,proto3" json:"messageId,omitempty"`
	TimeToLive           int64           `protobuf:"varint,5,opt,name=timeToLive,proto3" json:"timeToLive,omitempty"`
	Variables            *_struct.Struct `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageRecord) Reset()         { *m = MessageRecord{} }
func (m *MessageRecord) String() string { return proto.CompactTextString(m) }
func (*MessageRecord) ProtoMessage()    {}
func (*MessageRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{8}
}

func (m *MessageRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRecord.Unmarshal(m, b)
}
func (m *MessageRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRecord.Marshal(b, m, deterministic)
}
func (m *MessageRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRecord.Merge(m, src)
}
func (m *MessageRecord) XXX_Size() int {
	return xxx_messageInfo_MessageRecord.Size(m)
}
func (m *MessageRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRecord proto.InternalMessageInfo

func (m *MessageRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MessageRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageRecord) GetCorrelationKey() string {
	if m != nil {
		return m.CorrelationKey
	}
	return ""
}

func (m *MessageRecord) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageRecord) GetTimeToLive() int64 {
	if m != nil {
		return m.TimeToLive
	}
	return 0
}

func (m *MessageRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

type MessageSubscriptionRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,2,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	ElementInstanceKey   int64           `protobuf:"varint,3,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	MessageName          string          `protobuf:"bytes,4,opt,name=messageName,proto3" json:"messageName,omitempty"`
	CorrelationKey       string          `protobuf:"bytes,5,opt,name=correlationKey,proto3" json:"correlationKey,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,6,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	MessageKey           int64           `protobuf:"varint,7,opt,name=messageKey,proto3" json:"messageKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageSubscriptionRecord) Reset()         { *m = MessageSubscriptionRecord{} }
func (m *MessageSubscriptionRecord) String() string { return proto.CompactTextString(m) }
func (*MessageSubscriptionRecord) ProtoMessage()    {}
func (*MessageSubscriptionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{9}
}

func (m *MessageSubscriptionRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSubscriptionRecord.Unmarshal(m, b)
}
func (m *MessageSubscriptionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSubscriptionRecord.Marshal(b, m, deterministic)
}
func (m *MessageSubscriptionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSubscriptionRecord.Merge(m, src)
}
func (m *MessageSubscriptionRecord) XXX_Size() int {
	return xxx_messageInfo_MessageSubscriptionRecord.Size(m)
}
func (m *MessageSubscriptionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSubscriptionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSubscriptionRecord proto.InternalMessageInfo

func (m *MessageSubscriptionRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MessageSubscriptionRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *MessageSubscriptionRecord) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *MessageSubscriptionRecord) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *MessageSubscriptionRecord) GetCorrelationKey() string {
	if m != nil {
		return m.CorrelationKey
	}
	return ""
}

func (m *MessageSubscriptionRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *MessageSubscriptionRecord) GetMessageKey() int64 {
	if m != nil {
		return m.MessageKey
	}
	return 0
}

type MessageStartEventSubscriptionRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,2,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	StartEventId         string          `protobuf:"bytes,3,opt,name=startEventId,proto3" json:"startEventId,omitempty"`
	MessageName          string          `protobuf:"bytes,4,opt,name=messageName,proto3" json:"messageName,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,5,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageStartEventSubscriptionRecord) Reset()         { *m = MessageStartEventSubscriptionRecord{} }
func (m *MessageStartEventSubscriptionRecord) String() string { return proto.CompactTextString(m) }
func (*MessageStartEventSubscriptionRecord) ProtoMessage()    {}
func (*MessageStartEventSubscriptionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{10}
}

func (m *MessageStartEventSubscriptionRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStartEventSubscriptionRecord.Unmarshal(m, b)
}
func (m *MessageStartEventSubscriptionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStartEventSubscriptionRecord.Marshal(b, m, deterministic)
}
func (m *MessageStartEventSubscriptionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStartEventSubscriptionRecord.Merge(m, src)
}
func (m *MessageStartEventSubscriptionRecord) XXX_Size() int {
	return xxx_messageInfo_MessageStartEventSubscriptionRecord.Size(m)
}
func (m *MessageStartEventSubscriptionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStartEventSubscriptionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStartEventSubscriptionRecord proto.InternalMessageInfo

func (m *MessageStartEventSubscriptionRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MessageStartEventSubscriptionRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *MessageStartEventSubscriptionRecord) GetStartEventId() string {
	if m != nil {
		return m.StartEventId
	}
	return ""
}

func (m *MessageStartEventSubscriptionRecord) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *MessageStartEventSubscriptionRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

type TimerRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ElementInstanceKey   int64           `protobuf:"varint,2,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	DueDate              int64           `protobuf:"varint,3,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	Repetitions          int32           `protobuf:"varint,4,opt,name=repetitions,proto3" json:"repetitions,omitempty"`
	TargetFlowNodeId     string          `protobuf:"bytes,5,opt,name=targetFlowNodeId,proto3" json:"targetFlowNodeId,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,6,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,7,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TimerRecord) Reset()         { *m = TimerRecord{} }
func (m *TimerRecord) String() string { return proto.CompactTextString(m) }
func (*TimerRecord) ProtoMessage()    {}
func (*TimerRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{11}
}

func (m *TimerRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerRecord.Unmarshal(m, b)
}
func (m *TimerRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerRecord.Marshal(b, m, deterministic)
}
func (m *TimerRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerRecord.Merge(m, src)
}
func (m *TimerRecord) XXX_Size() int {
	return xxx_messageInfo_TimerRecord.Size(m)
}
func (m *TimerRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TimerRecord proto.InternalMessageInfo

func (m *TimerRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TimerRecord) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *TimerRecord) GetDueDate() int64 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

func (m *TimerRecord) GetRepetitions() int32 {
	if m != nil {
		return m.Repetitions
	}
	return 0
}

func (m *TimerRecord) GetTargetFlowNodeId() string {
	if m != nil {
		return m.TargetFlowNodeId
	}
	return ""
}

func (m *TimerRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *TimerRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

type VariableRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string          `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ScopeKey             int64           `protobuf:"varint,4,opt,name=scopeKey,proto3" json:"scopeKey,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,6,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VariableRecord) Reset()         { *m = VariableRecord{} }
func (m *VariableRecord) String() string { return proto.CompactTextString(m) }
func (*VariableRecord) ProtoMessage()    {}
func (*VariableRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{12}
}

func (m *VariableRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableRecord.Unmarshal(m, b)
}
func (m *VariableRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableRecord.Marshal(b, m, deterministic)
}
func (m *VariableRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableRecord.Merge(m, src)
}
func (m *VariableRecord) XXX_Size() int {
	return xxx_messageInfo_VariableRecord.Size(m)
}
func (m *VariableRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableRecord.DiscardUnknown(m)
}

var xxx_messageInfo_VariableRecord proto.InternalMessageInfo

func (m *VariableRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VariableRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VariableRecord) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *VariableRecord) GetScopeKey() int64 {
	if m != nil {
		return m.ScopeKey
	}
	return 0
}

func (m *VariableRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *VariableRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

type VariableDocumentRecord struct {
	Metadata             *RecordMetadata                        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ScopeKey             int64                                  `protobuf:"varint,2,opt,name=scopeKey,proto3" json:"scopeKey,omitempty"`
	UpdateSemantics      VariableDocumentRecord_UpdateSemantics `protobuf:"varint,3,opt,name=updateSemantics,proto3,enum=exporter_protocol.VariableDocumentRecord_UpdateSemantics" json:"updateSemantics,omitempty"`
	Variables            *_struct.Struct                        `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *VariableDocumentRecord) Reset()         { *m = VariableDocumentRecord{} }
func (m *VariableDocumentRecord) String() string { return proto.CompactTextString(m) }
func (*VariableDocumentRecord) ProtoMessage()    {}
func (*VariableDocumentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{13}
}

func (m *VariableDocumentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableDocumentRecord.Unmarshal(m, b)
}
func (m *VariableDocumentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableDocumentRecord.Marshal(b, m, deterministic)
}
func (m *VariableDocumentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableDocumentRecord.Merge(m, src)
}
func (m *VariableDocumentRecord) XXX_Size() int {
	return xxx_messageInfo_VariableDocumentRecord.Size(m)
}
func (m *VariableDocumentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableDocumentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_VariableDocumentRecord proto.InternalMessageInfo

func (m *VariableDocumentRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VariableDocumentRecord) GetScopeKey() int64 {
	if m != nil {
		return m.ScopeKey
	}
	return 0
}

func (m *VariableDocumentRecord) GetUpdateSemantics() VariableDocumentRecord_UpdateSemantics {
	if m != nil {
		return m.UpdateSemantics
	}
	return VariableDocumentRecord_UNKNOWN_UPDATE_SEMANTICS
}

func (m *VariableDocumentRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

type WorkflowInstanceRecord struct {
	Metadata                  *RecordMetadata                        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BpmnProcessId             string                                 `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version                   int32                                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey               int64                                  `protobuf:"varint,4,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	WorkflowInstanceKey       int64                                  `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	ElementId                 string                                 `protobuf:"bytes,6,opt,name=elementId,proto3" json:"elementId,omitempty"`
	FlowScopeKey              int64                                  `protobuf:"varint,7,opt,name=flowScopeKey,proto3" json:"flowScopeKey,omitempty"`
	BpmnElementType           WorkflowInstanceRecord_BpmnElementType `protobuf:"varint,8,opt,name=bpmnElementType,proto3,enum=exporter_protocol.WorkflowInstanceRecord_BpmnElementType" json:"bpmnElementType,omitempty"`
	ParentWorkflowInstanceKey int64                                  `protobuf:"varint,9,opt,name=parentWorkflowInstanceKey,proto3" json:"parentWorkflowInstanceKey,omitempty"`
	ParentElementInstanceKey  int64                                  `protobuf:"varint,10,opt,name=parentElementInstanceKey,proto3" json:"parentElementInstanceKey,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                               `json:"-"`
	XXX_unrecognized          []byte                                 `json:"-"`
	XXX_sizecache             int32                                  `json:"-"`
}

func (m *WorkflowInstanceRecord) Reset()         { *m = WorkflowInstanceRecord{} }
func (m *WorkflowInstanceRecord) String() string { return proto.CompactTextString(m) }
func (*WorkflowInstanceRecord) ProtoMessage()    {}
func (*WorkflowInstanceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{14}
}

func (m *WorkflowInstanceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowInstanceRecord.Unmarshal(m, b)
}
func (m *WorkflowInstanceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowInstanceRecord.Marshal(b, m, deterministic)
}
func (m *WorkflowInstanceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowInstanceRecord.Merge(m, src)
}
func (m *WorkflowInstanceRecord) XXX_Size() int {
	return xxx_messageInfo_WorkflowInstanceRecord.Size(m)
}
func (m *WorkflowInstanceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowInstanceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowInstanceRecord proto.InternalMessageInfo

func (m *WorkflowInstanceRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInstanceRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowInstanceRecord) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkflowInstanceRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *WorkflowInstanceRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceRecord) GetElementId() string {
	if m != nil {
		return m.ElementId
	}
	return ""
}

func (m *WorkflowInstanceRecord) GetFlowScopeKey() int64 {
	if m != nil {
		return m.FlowScopeKey
	}
	return 0
}

func (m *WorkflowInstanceRecord) GetBpmnElementType() WorkflowInstanceRecord_BpmnElementType {
	if m != nil {
		return m.BpmnElementType
	}
	return WorkflowInstanceRecord_UNKNOWN_BPMN_ELEMENT_TYPE
}

func (m *WorkflowInstanceRecord) GetParentWorkflowInstanceKey() int64 {
	if m != nil {
		return m.ParentWorkflowInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceRecord) GetParentElementInstanceKey() int64 {
	if m != nil {
		return m.ParentElementInstanceKey
	}
	return 0
}

type WorkflowInstanceCreationRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,4,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	Variables            *_struct.Struct `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorkflowInstanceCreationRecord) Reset()         { *m = WorkflowInstanceCreationRecord{} }
func (m *WorkflowInstanceCreationRecord) String() string { return proto.CompactTextString(m) }
func (*WorkflowInstanceCreationRecord) ProtoMessage()    {}
func (*WorkflowInstanceCreationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{15}
}

func (m *WorkflowInstanceCreationRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowInstanceCreationRecord.Unmarshal(m, b)
}
func (m *WorkflowInstanceCreationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowInstanceCreationRecord.Marshal(b, m, deterministic)
}
func (m *WorkflowInstanceCreationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowInstanceCreationRecord.Merge(m, src)
}
func (m *WorkflowInstanceCreationRecord) XXX_Size() int {
	return xxx_messageInfo_WorkflowInstanceCreationRecord.Size(m)
}
func (m *WorkflowInstanceCreationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowInstanceCreationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowInstanceCreationRecord proto.InternalMessageInfo

func (m *WorkflowInstanceCreationRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInstanceCreationRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowInstanceCreationRecord) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkflowInstanceCreationRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *WorkflowInstanceCreationRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceCreationRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

type WorkflowInstanceResultRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	WorkflowKey          int64           `protobuf:"varint,4,opt,name=workflowKey,proto3" json:"workflowKey,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,5,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	Variables            *_struct.Struct `protobuf:"bytes,6,opt,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorkflowInstanceResultRecord) Reset()         { *m = WorkflowInstanceResultRecord{} }
func (m *WorkflowInstanceResultRecord) String() string { return proto.CompactTextString(m) }
func (*WorkflowInstanceResultRecord) ProtoMessage()    {}
func (*WorkflowInstanceResultRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{16}
}

func (m *WorkflowInstanceResultRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowInstanceResultRecord.Unmarshal(m, b)
}
func (m *WorkflowInstanceResultRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowInstanceResultRecord.Marshal(b, m, deterministic)
}
func (m *WorkflowInstanceResultRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowInstanceResultRecord.Merge(m, src)
}
func (m *WorkflowInstanceResultRecord) XXX_Size() int {
	return xxx_messageInfo_WorkflowInstanceResultRecord.Size(m)
}
func (m *WorkflowInstanceResultRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowInstanceResultRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowInstanceResultRecord proto.InternalMessageInfo

func (m *WorkflowInstanceResultRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInstanceResultRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowInstanceResultRecord) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkflowInstanceResultRecord) GetWorkflowKey() int64 {
	if m != nil {
		return m.WorkflowKey
	}
	return 0
}

func (m *WorkflowInstanceResultRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceResultRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

type WorkflowInstanceSubscriptionRecord struct {
	Metadata             *RecordMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WorkflowInstanceKey  int64           `protobuf:"varint,2,opt,name=workflowInstanceKey,proto3" json:"workflowInstanceKey,omitempty"`
	ElementInstanceKey   int64           `protobuf:"varint,3,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	MessageName          string          `protobuf:"bytes,4,opt,name=messageName,proto3" json:"messageName,omitempty"`
	Variables            *_struct.Struct `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"`
	BpmnProcessId        string          `protobuf:"bytes,6,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	MessageKey           int64           `protobuf:"varint,7,opt,name=messageKey,proto3" json:"messageKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorkflowInstanceSubscriptionRecord) Reset()         { *m = WorkflowInstanceSubscriptionRecord{} }
func (m *WorkflowInstanceSubscriptionRecord) String() string { return proto.CompactTextString(m) }
func (*WorkflowInstanceSubscriptionRecord) ProtoMessage()    {}
func (*WorkflowInstanceSubscriptionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57ca2ff0dbf498b, []int{17}
}

func (m *WorkflowInstanceSubscriptionRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowInstanceSubscriptionRecord.Unmarshal(m, b)
}
func (m *WorkflowInstanceSubscriptionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowInstanceSubscriptionRecord.Marshal(b, m, deterministic)
}
func (m *WorkflowInstanceSubscriptionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowInstanceSubscriptionRecord.Merge(m, src)
}
func (m *WorkflowInstanceSubscriptionRecord) XXX_Size() int {
	return xxx_messageInfo_WorkflowInstanceSubscriptionRecord.Size(m)
}
func (m *WorkflowInstanceSubscriptionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowInstanceSubscriptionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowInstanceSubscriptionRecord proto.InternalMessageInfo

func (m *WorkflowInstanceSubscriptionRecord) GetMetadata() *RecordMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowInstanceSubscriptionRecord) GetWorkflowInstanceKey() int64 {
	if m != nil {
		return m.WorkflowInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceSubscriptionRecord) GetElementInstanceKey() int64 {
	if m != nil {
		return m.ElementInstanceKey
	}
	return 0
}

func (m *WorkflowInstanceSubscriptionRecord) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *WorkflowInstanceSubscriptionRecord) GetVariables() *_struct.Struct {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *WorkflowInstanceSubscriptionRecord) GetBpmnProcessId() string {
	if m != nil {
		return m.BpmnProcessId
	}
	return ""
}

func (m *WorkflowInstanceSubscriptionRecord) GetMessageKey() int64 {
	if m != nil {
		return m.MessageKey
	}
	return 0
}

func init() {
	proto.RegisterEnum("exporter_protocol.RecordMetadata_ValueType", RecordMetadata_ValueType_name, RecordMetadata_ValueType_value)
	proto.RegisterEnum("exporter_protocol.RecordMetadata_RecordType", RecordMetadata_RecordType_name, RecordMetadata_RecordType_value)
	proto.RegisterEnum("exporter_protocol.VariableDocumentRecord_UpdateSemantics", VariableDocumentRecord_UpdateSemantics_name, VariableDocumentRecord_UpdateSemantics_value)
	proto.RegisterEnum("exporter_protocol.WorkflowInstanceRecord_BpmnElementType", WorkflowInstanceRecord_BpmnElementType_name, WorkflowInstanceRecord_BpmnElementType_value)
	proto.RegisterType((*RecordId)(nil), "exporter_protocol.RecordId")
	proto.RegisterType((*Record)(nil), "exporter_protocol.Record")
	proto.RegisterType((*RecordMetadata)(nil), "exporter_protocol.RecordMetadata")
	proto.RegisterType((*DeploymentRecord)(nil), "exporter_protocol.DeploymentRecord")
	proto.RegisterType((*DeploymentRecord_Resource)(nil), "exporter_protocol.DeploymentRecord.Resource")
	proto.RegisterType((*DeploymentRecord_Workflow)(nil), "exporter_protocol.DeploymentRecord.Workflow")
	proto.RegisterType((*ErrorRecord)(nil), "exporter_protocol.ErrorRecord")
	proto.RegisterType((*IncidentRecord)(nil), "exporter_protocol.IncidentRecord")
	proto.RegisterType((*JobRecord)(nil), "exporter_protocol.JobRecord")
	proto.RegisterType((*JobBatchRecord)(nil), "exporter_protocol.JobBatchRecord")
	proto.RegisterType((*MessageRecord)(nil), "exporter_protocol.MessageRecord")
	proto.RegisterType((*MessageSubscriptionRecord)(nil), "exporter_protocol.MessageSubscriptionRecord")
	proto.RegisterType((*MessageStartEventSubscriptionRecord)(nil), "exporter_protocol.MessageStartEventSubscriptionRecord")
	proto.RegisterType((*TimerRecord)(nil), "exporter_protocol.TimerRecord")
	proto.RegisterType((*VariableRecord)(nil), "exporter_protocol.VariableRecord")
	proto.RegisterType((*VariableDocumentRecord)(nil), "exporter_protocol.VariableDocumentRecord")
	proto.RegisterType((*WorkflowInstanceRecord)(nil), "exporter_protocol.WorkflowInstanceRecord")
	proto.RegisterType((*WorkflowInstanceCreationRecord)(nil), "exporter_protocol.WorkflowInstanceCreationRecord")
	proto.RegisterType((*WorkflowInstanceResultRecord)(nil), "exporter_protocol.WorkflowInstanceResultRecord")
	proto.RegisterType((*WorkflowInstanceSubscriptionRecord)(nil), "exporter_protocol.WorkflowInstanceSubscriptionRecord")
}

func init() {
	proto.RegisterFile("proto/schema.proto", fileDescriptor_a57ca2ff0dbf498b)
}

var fileDescriptor_a57ca2ff0dbf498b = []byte{
	// 1907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x8e, 0xe3, 0x48,
	0x15, 0xde, 0x38, 0xff, 0x27, 0xdd, 0x69, 0x77, 0x4d, 0xef, 0x4c, 0xa6, 0x69, 0x5a, 0xc1, 0xac,
	0x50, 0x6b, 0x19, 0x65, 0x56, 0x8d, 0x40, 0x02, 0xb1, 0x17, 0x8e, 0x53, 0xb3, 0xe3, 0x1e, 0xc7,
	0x09, 0x65, 0x27, 0x4d, 0x73, 0x13, 0x39, 0x4e, 0xcd, 0x6c, 0x66, 0x12, 0x3b, 0xb2, 0x9d, 0x9e,
	0x69, 0x9e, 0x82, 0x17, 0xe0, 0x1e, 0x21, 0x71, 0xcf, 0x43, 0xec, 0x13, 0xec, 0x35, 0x42, 0xda,
	0x5b, 0x2e, 0x11, 0x12, 0xa8, 0xca, 0x3f, 0xf9, 0xb1, 0xb3, 0xd3, 0x0c, 0x41, 0x20, 0xc4, 0x9d,
	0xcf, 0x57, 0x55, 0xa7, 0x4e, 0x7d, 0xf5, 0x9d, 0x53, 0x55, 0x06, 0xb4, 0xf0, 0xdc, 0xc0, 0x7d,
	0xea, 0xdb, 0x5f, 0xd2, 0xb9, 0xd5, 0xe2, 0x06, 0x3a, 0xa6, 0xef, 0x16, 0xae, 0x17, 0x50, 0x6f,
	0xc4, 0x6d, 0xdb, 0x9d, 0x9d, 0x9e, 0xbd, 0x72, 0xdd, 0x57, 0x33, 0xfa, 0x94, 0x03, 0xe3, 0xe5,
	0xcb, 0xa7, 0x7e, 0xe0, 0x2d, 0xed, 0x20, 0x1c, 0x70, 0xfa, 0x78, 0xbb, 0xd5, 0x72, 0xee, 0xc2,
	0x26, 0xe9, 0x39, 0x54, 0x08, 0xb5, 0x5d, 0x6f, 0xa2, 0x4e, 0x50, 0x13, 0x6a, 0x0b, 0xcb, 0x0b,
	0xa6, 0xc1, 0xd4, 0x75, 0xd4, 0x49, 0x23, 0xd7, 0xcc, 0x5d, 0x14, 0xc9, 0x3a, 0x84, 0x4e, 0xa1,
	0xb2, 0x70, 0x7d, 0x6e, 0x35, 0x84, 0x66, 0xee, 0x22, 0x4f, 0x12, 0x5b, 0xfa, 0x09, 0x94, 0x42,
	0x4f, 0xe8, 0x09, 0x94, 0x3c, 0xfe, 0xc5, 0x5d, 0xd4, 0x2e, 0x4f, 0x5a, 0xe1, 0xfc, 0xad, 0x78,
	0xfe, 0x96, 0xec, 0xdc, 0x91, 0xa8, 0x8f, 0xf4, 0xe7, 0x12, 0xd4, 0xc3, 0x81, 0x5d, 0x1a, 0x58,
	0x13, 0x2b, 0xb0, 0xfe, 0xb5, 0x40, 0x90, 0x08, 0xf9, 0x37, 0xf4, 0xae, 0x91, 0xe7, 0x30, 0xfb,
	0x44, 0x67, 0x50, 0x0d, 0xa6, 0x73, 0xea, 0x07, 0xd6, 0x7c, 0xd1, 0x28, 0x70, 0x7c, 0x05, 0x20,
	0x0d, 0x20, 0x0c, 0xc5, 0xbc, 0x5b, 0xd0, 0x46, 0xb1, 0x99, 0xbb, 0xa8, 0x5f, 0x3e, 0x69, 0xa5,
	0x38, 0x6e, 0x6d, 0x06, 0x19, 0x99, 0x6c, 0x0c, 0x59, 0x1b, 0x8f, 0x1e, 0x42, 0x69, 0xea, 0x04,
	0xd4, 0x09, 0x1a, 0xa5, 0x66, 0xee, 0xa2, 0x4a, 0x22, 0x0b, 0xa9, 0x50, 0xbd, 0xb5, 0x66, 0x4b,
	0xca, 0x27, 0x29, 0xf3, 0x49, 0x7e, 0xf8, 0xfe, 0x49, 0x86, 0xf1, 0x10, 0xb2, 0x1a, 0x8d, 0x2e,
	0xe1, 0xc4, 0x77, 0x97, 0x9e, 0x4d, 0xc3, 0xce, 0xfd, 0x98, 0x88, 0x0a, 0x5f, 0x59, 0x66, 0x1b,
	0xfa, 0x04, 0x0e, 0x3d, 0xfa, 0x9a, 0xda, 0xcc, 0xe0, 0x21, 0x54, 0x79, 0x74, 0x9b, 0x20, 0xba,
	0x80, 0xa3, 0x04, 0x20, 0xd4, 0xf2, 0x5d, 0xa7, 0x01, 0xbc, 0xdf, 0x36, 0x2c, 0x7d, 0x2d, 0x40,
	0x35, 0x09, 0x0e, 0x3d, 0x04, 0x34, 0xd0, 0x5f, 0xe8, 0xbd, 0x6b, 0x7d, 0x34, 0x94, 0xb5, 0x01,
	0x1e, 0x99, 0x37, 0x7d, 0x2c, 0x7e, 0x84, 0xca, 0x90, 0xbf, 0xea, 0xb5, 0xc5, 0x1c, 0xaa, 0x03,
	0x74, 0x70, 0x5f, 0xeb, 0xdd, 0x74, 0xb1, 0x6e, 0x8a, 0x02, 0xfa, 0x18, 0x8e, 0xaf, 0x7b, 0xe4,
	0xc5, 0x33, 0xad, 0x77, 0x3d, 0x52, 0x75, 0xc3, 0x94, 0x75, 0x05, 0x8b, 0x79, 0x74, 0x00, 0x15,
	0x55, 0x57, 0xd4, 0x0e, 0xeb, 0x54, 0x40, 0x35, 0x28, 0x77, 0xb1, 0x61, 0xc8, 0x5f, 0x60, 0xb1,
	0x88, 0x1a, 0x70, 0x12, 0x19, 0x23, 0x63, 0xd0, 0x36, 0x14, 0xa2, 0xf6, 0x4d, 0xb5, 0xa7, 0x8b,
	0x25, 0x24, 0xc1, 0x79, 0xca, 0xd7, 0x66, 0x9f, 0x32, 0x3a, 0x84, 0xea, 0x55, 0xaf, 0x3d, 0x6a,
	0xcb, 0xa6, 0xf2, 0x5c, 0xac, 0xa0, 0x2a, 0x14, 0x4d, 0xb5, 0x8b, 0x89, 0x58, 0x45, 0x9f, 0x40,
	0x33, 0xf1, 0x6b, 0xca, 0xc4, 0x1c, 0xe1, 0x21, 0xd6, 0xcd, 0xcd, 0xf1, 0xc0, 0x02, 0x1b, 0xca,
	0x44, 0x95, 0xdb, 0x1a, 0x16, 0x6b, 0x2c, 0xfa, 0xd8, 0x1a, 0x75, 0x7a, 0xca, 0x80, 0x2f, 0xea,
	0x00, 0x9d, 0xc3, 0x69, 0x3a, 0x10, 0x85, 0x60, 0x99, 0x3b, 0x39, 0x64, 0xb3, 0x62, 0x42, 0x7a,
	0x44, 0xac, 0xa3, 0x33, 0x68, 0xa4, 0xbb, 0x12, 0x6c, 0x0c, 0x34, 0x53, 0x3c, 0x92, 0x4c, 0x80,
	0x95, 0xba, 0xd0, 0x23, 0x78, 0x10, 0x93, 0x4b, 0xb0, 0xd2, 0x23, 0x9d, 0x98, 0x5d, 0xe6, 0x8f,
	0x05, 0x2b, 0xe6, 0x18, 0x55, 0x4a, 0xaf, 0xdb, 0x95, 0xf5, 0x4e, 0x48, 0x6e, 0x64, 0x8c, 0x08,
	0xbe, 0xc2, 0x0a, 0x9f, 0x3e, 0x2f, 0xfd, 0x2d, 0x0f, 0x62, 0x87, 0x2e, 0x66, 0xee, 0xdd, 0x9c,
	0x3a, 0x41, 0x94, 0xab, 0x9f, 0x43, 0x65, 0x1e, 0x89, 0x2d, 0xca, 0xd6, 0xef, 0xbd, 0x57, 0x95,
	0x24, 0x19, 0x82, 0xae, 0xa0, 0xea, 0xd1, 0x50, 0x70, 0x7e, 0x43, 0x68, 0xe6, 0x2f, 0x6a, 0x99,
	0xa9, 0xb3, 0x3d, 0x6d, 0x8b, 0x44, 0x83, 0xc8, 0x6a, 0x38, 0xfa, 0x15, 0x1c, 0x4f, 0x78, 0x3f,
	0x3a, 0xb9, 0x76, 0xbd, 0x37, 0x2f, 0x67, 0xee, 0x5b, 0xbf, 0x91, 0xbf, 0xbf, 0xcf, 0x78, 0x10,
	0x49, 0xbb, 0x39, 0x75, 0x58, 0x99, 0x0b, 0x27, 0x62, 0xb5, 0x23, 0x9e, 0x94, 0x2f, 0xf9, 0x80,
	0x24, 0x36, 0x92, 0xe0, 0x20, 0xfe, 0xe6, 0x59, 0x22, 0x70, 0xf5, 0x6f, 0x60, 0xeb, 0x7d, 0x74,
	0x6b, 0x4e, 0x79, 0xa1, 0x59, 0xeb, 0xc3, 0xb0, 0xd3, 0xdf, 0xe4, 0xa0, 0x12, 0xcf, 0xce, 0x72,
	0x6f, 0xbc, 0x98, 0x3b, 0x7d, 0xcf, 0xb5, 0xa9, 0xef, 0x47, 0x05, 0xad, 0x4a, 0x36, 0x41, 0xd4,
	0x80, 0xf2, 0x2d, 0xf5, 0xfc, 0xb8, 0xa2, 0x15, 0x49, 0x6c, 0xb2, 0x72, 0xf8, 0x36, 0xf2, 0xf5,
	0x22, 0x29, 0x6c, 0xeb, 0x50, 0x2a, 0xa4, 0x62, 0x3a, 0x24, 0xe9, 0xaf, 0x39, 0xa8, 0x61, 0xcf,
	0x73, 0xbd, 0xfd, 0xec, 0xfc, 0xa7, 0x20, 0xd2, 0x77, 0x36, 0x5d, 0xb0, 0x9a, 0xd0, 0xa5, 0xbe,
	0x6f, 0xbd, 0x8a, 0xd9, 0x4a, 0xe1, 0xe8, 0x1c, 0xc0, 0x0f, 0x2c, 0xfb, 0x4d, 0xe0, 0x59, 0x76,
	0xcc, 0xd7, 0x1a, 0x82, 0x5a, 0x80, 0x28, 0x8b, 0x0c, 0xdf, 0x52, 0x27, 0x48, 0xca, 0x59, 0x58,
	0xa8, 0x33, 0x5a, 0xd0, 0x67, 0xf0, 0x20, 0x5e, 0xbd, 0xea, 0xf8, 0x81, 0xe5, 0xd8, 0x94, 0x11,
	0x53, 0xe4, 0x03, 0xb2, 0x9a, 0xa4, 0xdf, 0xe6, 0xa1, 0xae, 0x3a, 0xf6, 0x74, 0xb2, 0x37, 0xe5,
	0x9f, 0x41, 0x95, 0x47, 0xb6, 0x26, 0x93, 0x15, 0xc0, 0x36, 0x84, 0x1b, 0x31, 0x33, 0x91, 0x46,
	0xd6, 0xb1, 0xb4, 0x2c, 0x0a, 0x59, 0xb2, 0xf8, 0xa7, 0xd7, 0xca, 0x23, 0x9b, 0x51, 0x96, 0x18,
	0xea, 0x24, 0x3a, 0x84, 0x56, 0x00, 0xe7, 0x3a, 0x32, 0xd6, 0xdc, 0x95, 0x23, 0xae, 0x53, 0x2d,
	0xec, 0x3c, 0x7b, 0xed, 0x8e, 0x59, 0x9f, 0xf0, 0x78, 0x89, 0xac, 0x6d, 0x51, 0x56, 0xd3, 0xa2,
	0xfc, 0x14, 0xc4, 0x5b, 0xcb, 0x9b, 0x5a, 0xe3, 0x19, 0x35, 0x6c, 0x77, 0xc1, 0xe7, 0x01, 0xde,
	0x2d, 0x85, 0x4b, 0x5f, 0x15, 0xa0, 0x7a, 0xe5, 0x8e, 0xf7, 0xb3, 0x35, 0x08, 0x0a, 0xc1, 0x6a,
	0x57, 0xf8, 0x37, 0x5b, 0x06, 0x8b, 0x8d, 0x7a, 0xd1, 0x56, 0x44, 0x16, 0xcb, 0x3a, 0x8f, 0x06,
	0xde, 0x94, 0xfa, 0x9c, 0xfe, 0x22, 0x89, 0x4d, 0x56, 0x26, 0x26, 0xd4, 0x9a, 0xcc, 0xa6, 0x0e,
	0x8d, 0xd8, 0x4e, 0xec, 0xd4, 0xf6, 0x96, 0x32, 0xb6, 0xf7, 0x73, 0x38, 0xb4, 0x97, 0x7e, 0xe0,
	0xce, 0x9f, 0x53, 0x6b, 0x42, 0x3d, 0x9f, 0x73, 0x5c, 0xbb, 0x7c, 0x94, 0xba, 0x0c, 0x19, 0xfc,
	0xaa, 0x46, 0x36, 0x7b, 0xa3, 0x1f, 0xb3, 0xfb, 0x42, 0xc8, 0x92, 0xcf, 0xa9, 0xff, 0x96, 0xa1,
	0xab, 0x9e, 0x9b, 0x9b, 0x5f, 0xbd, 0xdf, 0xe6, 0xc3, 0xce, 0xcd, 0x4f, 0x49, 0xb4, 0x96, 0x25,
	0xd1, 0x9f, 0xc3, 0xe3, 0x78, 0xdf, 0x3b, 0xf4, 0xe5, 0xd4, 0xe1, 0x49, 0x3a, 0x8c, 0x6a, 0xd9,
	0x01, 0x67, 0x75, 0x77, 0x87, 0x5d, 0x02, 0x3f, 0xdc, 0x2d, 0xf0, 0x2d, 0xe9, 0xd5, 0x53, 0xd2,
	0x93, 0xfe, 0x20, 0x40, 0xfd, 0xca, 0x1d, 0xb7, 0xad, 0xc0, 0xfe, 0xf2, 0x3f, 0xa2, 0x29, 0x76,
	0xbb, 0x74, 0x97, 0x41, 0x54, 0xc3, 0x62, 0x13, 0x3d, 0x81, 0xe3, 0xb9, 0xf5, 0xee, 0xca, 0x1d,
	0xfb, 0xa6, 0x2b, 0xdb, 0xc1, 0xf4, 0xd6, 0x0a, 0x42, 0x71, 0x15, 0x49, 0xba, 0x81, 0xf9, 0x09,
	0x93, 0xcd, 0x6f, 0x94, 0x9a, 0x79, 0xe6, 0x27, 0x32, 0xd1, 0x67, 0x50, 0x78, 0xed, 0x8e, 0x99,
	0xa4, 0xd8, 0xe9, 0x78, 0x96, 0xb1, 0x90, 0x24, 0x99, 0x08, 0xef, 0xc9, 0xaf, 0xc0, 0xde, 0xd2,
	0xb1, 0xad, 0x80, 0x4e, 0xb8, 0x9c, 0x2a, 0x64, 0x05, 0x48, 0x7f, 0xcf, 0xc1, 0x61, 0xa4, 0xdb,
	0xbd, 0xd1, 0xe5, 0xb0, 0x83, 0x28, 0xa2, 0x8b, 0x7d, 0xa3, 0x1f, 0x40, 0xdd, 0x76, 0x3d, 0x8f,
	0xce, 0x2c, 0xb6, 0xfd, 0xf1, 0x49, 0x56, 0x25, 0x5b, 0x28, 0x0b, 0x75, 0x1e, 0xc6, 0x92, 0xd4,
	0xc4, 0x15, 0xc0, 0xce, 0x12, 0xc6, 0xa6, 0xe9, 0x6a, 0xd3, 0xdb, 0x38, 0x31, 0xd7, 0x90, 0xcd,
	0xbc, 0x29, 0xdd, 0x37, 0x6f, 0xa4, 0xaf, 0x04, 0x78, 0x1c, 0x31, 0x60, 0x2c, 0xc7, 0xbe, 0xed,
	0x4d, 0x17, 0xe1, 0x6d, 0x77, 0x1f, 0x6c, 0xec, 0x90, 0xb8, 0xb0, 0x5b, 0xe2, 0xd9, 0x89, 0x9a,
	0xdf, 0x99, 0xa8, 0x4d, 0xa8, 0x45, 0x14, 0xf1, 0xf3, 0x3f, 0x64, 0x6d, 0x1d, 0xca, 0x60, 0xbf,
	0x98, 0xc9, 0x7e, 0x2a, 0xe5, 0x4b, 0x59, 0x29, 0x7f, 0x0e, 0x10, 0x39, 0x5f, 0x9d, 0x1e, 0x6b,
	0x88, 0xf4, 0x97, 0x1c, 0x7c, 0x3f, 0xa6, 0x33, 0xb0, 0xbc, 0x80, 0x9f, 0xdf, 0xfb, 0x27, 0x76,
	0xab, 0x12, 0x08, 0x99, 0x37, 0x23, 0x3f, 0x09, 0x40, 0x9d, 0xc4, 0x07, 0xf1, 0x3a, 0x76, 0x0f,
	0xf2, 0x52, 0xa4, 0x14, 0x33, 0x48, 0x91, 0xfe, 0x28, 0x40, 0xcd, 0x9c, 0xce, 0xe9, 0x9e, 0x6e,
	0x58, 0xd9, 0x1a, 0x10, 0x76, 0x6a, 0xa0, 0x01, 0xe5, 0xc9, 0x92, 0x76, 0x58, 0x49, 0x09, 0x85,
	0x12, 0x9b, 0x6c, 0x81, 0x1e, 0x5d, 0xd0, 0xf0, 0xf5, 0x1c, 0x1f, 0x74, 0xeb, 0x10, 0x3b, 0xab,
	0x03, 0xcb, 0x7b, 0x45, 0x83, 0x67, 0x33, 0xf7, 0xad, 0xee, 0x4e, 0x68, 0xb2, 0xc6, 0x14, 0xbe,
	0x4b, 0xcd, 0xa5, 0x7b, 0x17, 0xec, 0x72, 0xba, 0x60, 0x7f, 0x93, 0x83, 0xfa, 0x30, 0x4a, 0xc6,
	0x7f, 0x5f, 0x05, 0x3a, 0x81, 0x22, 0x7f, 0x45, 0x47, 0x2a, 0x08, 0x0d, 0x76, 0xd0, 0xfb, 0xf1,
	0xfd, 0x24, 0xac, 0xd7, 0x89, 0xfd, 0x01, 0xb7, 0xaf, 0xad, 0xb5, 0x96, 0xd2, 0x6b, 0xfd, 0x5a,
	0x80, 0x87, 0xf1, 0x5a, 0x3b, 0xae, 0xbd, 0xdc, 0xdf, 0x6b, 0x6c, 0x7d, 0x25, 0xc2, 0xd6, 0x4a,
	0x6c, 0x38, 0x5a, 0x2e, 0x26, 0x56, 0x40, 0x0d, 0x3a, 0xb7, 0x9c, 0x60, 0x6a, 0xfb, 0x9c, 0x85,
	0xfa, 0xe5, 0x4f, 0x33, 0x66, 0xc8, 0x0e, 0xaf, 0x35, 0xd8, 0x74, 0x40, 0xb6, 0x3d, 0x6e, 0x16,
	0xdf, 0xc2, 0xbd, 0x8b, 0xaf, 0x0a, 0x47, 0x5b, 0xae, 0xd9, 0x03, 0x39, 0x7e, 0xf4, 0x0e, 0xfa,
	0x1d, 0xd9, 0xc4, 0x23, 0x03, 0x77, 0x65, 0xdd, 0x54, 0x15, 0x23, 0x7c, 0xf9, 0x6a, 0x3d, 0x45,
	0xd6, 0xc4, 0x1c, 0x7b, 0xd9, 0xf7, 0x49, 0xaf, 0x2f, 0x7f, 0x21, 0x9b, 0x58, 0x14, 0xa4, 0x6f,
	0x4a, 0xf0, 0xf0, 0x7a, 0x6b, 0x5b, 0xf6, 0x43, 0x6e, 0xaa, 0x06, 0x08, 0xef, 0x79, 0xc5, 0xe5,
	0xbf, 0xf5, 0x15, 0x57, 0x48, 0xd7, 0xaa, 0x7d, 0x5f, 0xf5, 0x25, 0x38, 0x60, 0x03, 0x92, 0xcb,
	0x77, 0x98, 0x77, 0x1b, 0x18, 0x93, 0x05, 0x5b, 0x00, 0x0e, 0x07, 0xf1, 0xc7, 0x4c, 0x65, 0xa7,
	0x2c, 0xb2, 0x89, 0x6d, 0xb5, 0x37, 0x1d, 0x90, 0x6d, 0x8f, 0xec, 0x82, 0xb8, 0xb0, 0x3c, 0xea,
	0x04, 0xd7, 0x19, 0xcb, 0x0b, 0x5f, 0x0e, 0xbb, 0x3b, 0xa0, 0x9f, 0x41, 0x23, 0x6c, 0xc4, 0xbb,
	0xae, 0xae, 0x3b, 0xdb, 0x59, 0xae, 0x1d, 0x6d, 0x85, 0x87, 0xbe, 0x0b, 0x8f, 0x63, 0x69, 0xb5,
	0xfb, 0x5d, 0x7d, 0x84, 0x35, 0xdc, 0xc5, 0xba, 0x19, 0xff, 0x55, 0x39, 0x82, 0xda, 0x40, 0x37,
	0xfa, 0x58, 0x51, 0x9f, 0xa9, 0xb8, 0x13, 0xfe, 0x5b, 0xe9, 0x93, 0x9e, 0x82, 0x0d, 0x43, 0x14,
	0x58, 0xab, 0x31, 0x68, 0x8f, 0x62, 0x20, 0xcf, 0x81, 0xd5, 0x7f, 0x23, 0xb1, 0xc0, 0x94, 0xab,
	0xea, 0x26, 0x26, 0x5d, 0xdc, 0x51, 0x99, 0x6e, 0x15, 0xd9, 0x54, 0x9e, 0x47, 0xad, 0x45, 0x84,
	0xa0, 0xde, 0xee, 0x0d, 0xf4, 0x8e, 0x4c, 0x6e, 0x22, 0xac, 0xc4, 0x24, 0x8c, 0xf5, 0x4e, 0x64,
	0x96, 0x91, 0x08, 0x07, 0x06, 0x26, 0x43, 0x55, 0xc1, 0x23, 0x53, 0x36, 0x5e, 0x88, 0x15, 0x86,
	0x10, 0xac, 0x60, 0x75, 0x18, 0x21, 0x55, 0xf4, 0x31, 0x1c, 0xe3, 0x5f, 0x2a, 0xda, 0xc0, 0x60,
	0x18, 0x93, 0xfe, 0xb5, 0x7c, 0x23, 0x02, 0x3a, 0x01, 0xb1, 0x2f, 0x13, 0x59, 0xd3, 0xb0, 0x96,
	0xa0, 0x35, 0xf4, 0x08, 0x1e, 0x84, 0x3f, 0xb5, 0xda, 0xb2, 0x81, 0x3b, 0x49, 0xc3, 0x01, 0x3a,
	0x86, 0x43, 0x03, 0xff, 0x62, 0x80, 0x75, 0x05, 0x8f, 0x9e, 0x69, 0xbd, 0x6b, 0xf1, 0x90, 0xf5,
	0xed, 0x0e, 0x34, 0x53, 0x5d, 0xfd, 0x95, 0x6a, 0xf7, 0x3a, 0x37, 0x62, 0x9d, 0xf5, 0x55, 0x64,
	0x4d, 0x1b, 0xc9, 0x8a, 0xa9, 0x0e, 0x55, 0xf3, 0x46, 0x3c, 0x92, 0x7e, 0x2f, 0xc0, 0xf9, 0xf6,
	0x86, 0x29, 0x1e, 0xb5, 0xf6, 0x77, 0xbe, 0xff, 0x37, 0xe6, 0xdc, 0x07, 0x5e, 0x30, 0x7f, 0x27,
	0xc0, 0x59, 0x3a, 0x7f, 0xfc, 0xe5, 0x2c, 0xf8, 0x3f, 0x55, 0x5b, 0x54, 0xfd, 0x49, 0x00, 0x69,
	0x9b, 0xaa, 0xff, 0xcd, 0x4b, 0xf9, 0x06, 0x41, 0xc5, 0x7b, 0x3f, 0xf2, 0xf7, 0x72, 0x47, 0x6f,
	0x7f, 0x07, 0x1e, 0x4d, 0xdd, 0xd6, 0xaf, 0x29, 0x1d, 0xd3, 0x84, 0xb7, 0x70, 0xd6, 0xfe, 0x47,
	0xe3, 0x12, 0xff, 0xf8, 0xd1, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd0, 0xd6, 0x74, 0x80,
	0x1a, 0x00, 0x00,
}
